#%RAML 1.0
title: Hash-system REST API msisdns
protocols: [ HTTP ]
baseUri: http://{environment}/api
securitySchemes:
  basic:
    type: Basic Authentication

mediaType: application/json

types:

  Response: |
  {
    "type": "object"
    "properties": {
      "value": {
        "title": "hash by msisdn",
        "type": "string"
      }
    }
  }

  Error: |
  {
    "type": "object"
    "properties": {
      "errorId": {
        "title": "Error Id.",
        "type": "integer"
      },
      "errorMsg": {
        "title": "Error description.",
        "type": "string"
      }
    }
  }

/msisdns/{hash}:
  get:
    description: Get msisdn by hash.
    responses:
      200:
        body:
          type: Response
          example: |
          {
            "value": "380672244089"
          }
      400:
        description: Hash is incorrect.
        body:
          type: Error
          example: |
          {
            "errorId": 5,
            "errorMsg": "Incorrect MSISDN format"
          }
      401:
        description: Login and password is not present or incorrect in request.
      403:
        description: Ip adress not allowed for this login.
      404:
        description: Msisdn by hash not exists.
        body:
          type: Error
          example: |
          {
            "errorId": 2,
            "errorMsg": "Data not found"
          }
      500:
        description: Server error
        body:
          type: Error
          example: |
          {
            "errorId": 99,
            "errorMsg": "Internal error"
          }